# Generated by Django 3.2.15 on 2022-09-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_alter_user_isfirsttimelogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isFirstTimeLogin',
            field=models.BooleanField(default=1),
        ),
    ]
